### PR TITLE
stub commit of spots needed for any angle belted printing

### PR DESCRIPTION
**Pull request by cartazio**
hello! 
i was poking at whats needed to add configurable support for "any angle" belted printers, and I think i found all the magic constants that need editing, how would i turn that into an exposed configuration knob on the machine time (and thus ideally have that be something easy to upstream)?

thx

### CODE REVIEW

**Comment by stewartoallen** [comment]
have you tested this? there are a few more places (like supports) where the code takes advantage of unique attributes of 45 degree angles and simple math.

**Comment by cartazio** [comment]
That stub set of constants is me pretending to have the gantry parallel to
the table so the layers are in the xz plane. It did give me what look like
vertical slices when I ran it on the sample cube shape.

1) what are the tests you’d look for ?

2) if I were to turn these (and perhaps other spots ) into soemthing that
reads off a printer Config variable, how would you like that organized?

**Comment by stewartoallen** [comment]
you would need to export and re-import gcode and run some jobs to verify. but I strongly believe based on the previous belt work that it's not this simple. there are a lot of subtleties with offsets, anchors, level detection, and more where it can go wrong. its possible the preview is misleading in this respect. but if it could be made to work, I would replace the belt checkbox with an input box that accepts angle. either that, or when belt is enabled on a device, add a new angle field on the right-hand menu.

**Comment by stewartoallen** [comment]
I re-worked the belt code for 4.0 and it now supports arbitrary angles.

**Pull request closed without merging**
