### PR TITLE
Start desktop implementation with nw.js (#129)

### PR DESCRIPTION
**Pull request by pbek**
This could be the start of the desktop implementation using https://nwjs.io/.
Starting the app already works.

```bash
# install devDependencies
npm i
# start gs-app-server and run the desktop app via nw.js
npm run start
```

But I still have some issues with building the desktop app for distribution.
Under Linux you can try a `npm run build:lin` and look into the directory `./dist/grid-apps-3.0.15D-linux-x64/`.
It never stops building and there are always more files generated.
If you look into `dist/grid-apps-3.0.15D-linux-x64/apps/grid/` you'll see what I mean. Any suggestions?

### CODE REVIEW

**Comment by pbek** [comment]
Slicing doesn't seem to do anything yet, does the error message `[72859:72867:0730/221454.608901:ERROR:cert_verify_proc_builtin.cc(559)] No net_fetcher for performing AIA chasing.` have anything to do with it?

**Comment by stewartoallen** [comment]
i'm going to be tied up for a couple of weeks. the environment needs to support WASM even if that limits it to chromium since current and future code relies on it.

**Comment by pbek** [comment]
Shouldn't be an issue, since nw.js uses Chromium.

**Comment by pbek** [comment]
> the environment needs to support WASM

So if slicing doesn't work it's an indication that WASM isn't working yet in the desktop app?

**Comment by pbek** [comment]
I tried on my other dev machine. Slicing worked just fine there...

image

**Comment by pbek** [comment]
> It never stops building and there are always more files generated.
> If you look into dist/grid-apps-3.0.15D-linux-x64/apps/grid/ you'll see what I mean. Any suggestions?

@stewartoallen, I think I know where that comes from, you have a infinite sym-link loop in https://github.com/GridSpace/grid-apps/tree/master/apps! Is that on purpose?

**Comment by pbek** [comment]
The binary distribution is now created successfully with `npm run build:lin` and it runs with `./dist/grid-apps-3.0.15D-linux-x64/grid-apps`, but I still have troubles with the slicer now and then.

**Comment by pbek** [comment]
Slicing seems to work fine now in the Linux build. 👍🏻 
I also run the server on a higher port now so it doesn't collide with other services.

**Comment by stewartoallen** [comment]
I will review this next week when I have office space again. thanks for putting this together.

**Comment by pbek** [comment]
Great, I'm just working on the build process in a GitHub Action workflow. 😁 
Currently building on https://github.com/pbek/grid-apps/runs/3233500225?check_suite_focus=true

**Comment by pbek** [comment]
I managed to bring down the size of the archives down pretty low now. You can test them by downloading the artifacts on https://github.com/pbek/grid-apps/actions/runs/1098788413 (don't get distracted by that artefacts are zips in zips, that's a restriction of the artifact system, the github releases don't have that restriction)

**Comment by pbek** [comment]
The build time is now down to under 5min too...

**Comment by pbek** [comment]
Btw. the app name `grid-apps` is bound to:

https://github.com/GridSpace/grid-apps/blob/cb17b786689c9bbb9f889eee7af7980030da95c1/package.json#L2

But the desktop build is customized for kiri:moto...
Is there a special reason for the name `grid-apps`? I currently don't see any other apps than kiri:moto in it 😁

**Comment by pbek** [comment]
The Windows build took "some" more work. 😅 
And I'm renaming the package now to `kiri-moto` at build time to get the name for the binaries right.

**Comment by pbek** [comment]
> I will review this next week when I have office space again. thanks for putting this together.

You did? 😁

**Comment by stewartoallen** [comment]
just got back. is it possible to build on mac as well, or is this windows only?

**Comment by pbek** [comment]
I had some issues building for Windows on Linux so I chose to build on Windows in the CI. If you are working on macOS you should at least have no issue building for macOS (and Linux) for testing. For releases I would suggest Github Actions. I can create you a workflow that could create a release for you.

**Comment by stewartoallen** [comment]
take a look at the full PWA implementation of Kiri:Moto that allows it to be "installed" as an app through the browser. once linked or added to your home screen, it does not require an internet connection to load and run.

https://twitter.com/grid_space_3d/status/1565398789942386688

**Pull request closed without merging**
