### PR TITLE
overcut feature

### PR DESCRIPTION
**Pull request by Type8**
Hi.

Well, in the next weeks I will need to mill some wood junctions.
So, I needed a way to eliminate the problem of the "rounded" inside corner without manual post process the pieces (sanding basically).
I could do an hole in the file and use the drill feature, i know but i prefer a quickest way.

I did not found this feature in Kiri:Moto, so I implemented it.

Basically it is an overcut in some user-selected points.
I duplicated the code you wrote for the tabs positioning and I modified it in order to draw a red cylinder instead of a box.
Then, during the "slicing", if I find some "overcut" object in the "overcuts" property of settings.widget[widget.id] I add a small 32 point polygon to the points collection (a small circle inside the cylinder).
The radius of this small circle is calculated as: 

`oc.dim.radiusbottom - outlineToolDiam/2`

where the radiusbottom is a property of the Three.js red cylinder and it the radius value selected by the user.

The feature can be triggered in the outline phase (i don't know actually if it is 100% correct) inserting a radius bigger than 0.

overcut_setting_0

This value is in MM. I am not so confident with the inches, so i prefered to use millimiters.
Three buttons will appear and they work like the tabs ones. Here the user can add one or more of this overcut cylinders on the faces.

overcut_setting_2

For sure I am not able to test all the feature of Kiri:Moto, so I can only hope I did not create some regression somewhere in the code.
Also the positiong is not perfect, it would be great to have the possibility to anchor the cylinders to the edges (now they are anchored to the vertical faces like the tabs). 

overcut_plater
overcut_preview

Here the result with a radius of 2 mm (I will definitely increase a bit this value for my jobs):

I hope you'll find this feature interesting like I do.. keeping in mind that this is an experimental feature that can be improve a lot.

Take care, Umberto.

### CODE REVIEW

**Comment by stewartoallen** [comment]
Love it. These are sometime called "dog bones" and they were already on my todo list. I'll take a look at your implementation and see if it's a starting point I could use. Thanks for taking the time to put this together.

**Comment by stewartoallen** [comment]
Looking through the code, the UI elements are re-usable (like tabs and traces). There are three basic ways to do a dog-bone. Most are a linear extension to an existing path rather than a separate path (like the polygon you're creating). This is more efficient and continuous. I'll think about it more tonight. The code should identify and highlight these features automatically. Not hard, actually, given they're vertical faces with acute interior angles.

**Comment by Type8** [comment]
>  The code should identify and highlight these features automatically. Not hard, actually, given they're vertical faces with acute interior angles.

Totally agree with this. Identify acute angles is not complex. Select the ones that are acute and "interior" is not... :(

**Comment by stewartoallen** [comment]
I've added a simpler version of this in the current development release. No UI or selection, just a checkbox. In 2.5 I will revisit this as part of a whole reflow of the CAM process model. It will make a lot more sense and be far more customizable then,

https://youtu.be/H6avz0Vnrv0

**Comment by Type8** [comment]
just checked your video about it. Your solution it seems way more efficient than mine. Now I am curious to check your implementation... I will merge your master to mine :)

PS. "dogbones" is even cooler than "overcut" :P

**Pull request closed without merging**
